const mockEvents=[
      { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"24/05/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
     { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"31/05/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
      { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"07/06/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
      { "event":"5K Run",
        "location":"London Irish Centre Camden",
        "image":"lic.jpg",
        "coordinates":"https://maps.app.goo.gl/xYLbUNMr6m4z9Mzx6",
        "date":"11/06/2025",
        "time":"18:30pm",
        "bagDrop":true,
        "description":"Meeting point at The London Irish Centre, Camden for a casual 5k to Primrose Hill and back; Finishing at the London Irish centre for a post run pint, with live trad music"
      },
      { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"14/06/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
      
      { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"21/06/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
      
      { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"28/06/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
       { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"05/07/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
       { "event":"5K Run",
        "location":"Hyde Park Corner",
        "image":"hyde-park.png",
        "coordinates":"https://maps.app.goo.gl/bwv9CK4D8rY3xSPW6",
        "date":"12/07/2025",
        "time":"9:15am",
        "bagDrop":false,
        "description":"Meeting point at The Lodge cafe Hyde park corner for a casual 5k; Finishing at the serpintine cafe for a post run coffee and social"
      },
      { "event":"5K Run",
        "location":"London Irish Centre Camden",
        "image":"lic.jpg",
        "coordinates":"https://maps.app.goo.gl/xYLbUNMr6m4z9Mzx6",
        "date":"05/07/2025",
        "time":"18:30pm",
        "bagDrop":true,
        "description":"Meeting point at The London Irish Centre, Camden for a casual 5k to Primrose Hill and back; Finishing at the London Irish centre for a post run pint, with live trad music"
      },
      { "event":"5K Run",
        "location":"London Irish Centre Camden",
        "image":"lic.jpg",
        "coordinates":"https://maps.app.goo.gl/xYLbUNMr6m4z9Mzx6",
        "date":"09/07/2025",
        "time":"18:30pm",
        "bagDrop":true,
        "description":"Meeting point at The London Irish Centre, Camden for a casual 5k to Primrose Hill and back; Finishing at the London Irish centre for a post run pint, with live trad music"
      }

    ];
export default mockEvents;